FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build
WORKDIR /src

ARG RID=linux-musl-x64

COPY *.csproj ./
RUN dotnet restore -r $RID

COPY . ./

RUN dotnet publish -c Release -r $RID -o /app/publish --self-contained false

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine
WORKDIR /app

RUN apk add --no-cache ffmpeg libmsquic

COPY --from=build /app/publish .

EXPOSE 8080
ENV DOTNET_URLS=http://+:8080
ENV DOTNET_RUNNING_IN_CONTAINER=true

ENTRYPOINT ["dotnet", "TwitchRecorderApi.dll"]
